# Generated by Django 4.2.7 on 2025-08-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='skillora_app.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_progress_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='upcoming_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='skillora_app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
