# Generated by Django 4.2.7 on 2025-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0002_course_students_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='liked_courses',
            field=models.ManyToManyField(blank=True, related_name='liked_by_students', to='skillora_app.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='saved_courses',
            field=models.ManyToManyField(blank=True, related_name='saved_by_students', to='skillora_app.course'),
        ),
    ]
