# Generated by Django 5.2.5 on 2025-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0003_student_liked_courses_student_saved_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='liked_courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
