# Generated by Django 5.2.5 on 2025-08-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0005_attendancesession_testsession_attendancerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='testrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='session',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='course',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
        migrations.DeleteModel(
            name='TestRecord',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
