# Generated by Django 5.2.5 on 2025-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillora_app', '0006_remove_attendancesession_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_type',
            field=models.CharField(default='Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(default='Life Time', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
